### ISSUE TITLE
Should we use SCSS

### ISSUE THREAD

**Issue by PineappleRind** [discordutilitybot/utility-bot-website#1]
Should we use SCSS? It could be useful with many things. There are many SCSS compiler extensions on vscode.

**Comment by TheCodingGuru** [comment]
Sure 🤜🤛

**Comment by TheCodingGuru** [comment]
Let's wait till @andrewnijmeh replies!

**Comment by PineappleRind** [comment]
Great!

**Comment by andrewnijmeh** [comment]
Sure sounds good color variables are really good and you can even implement functions thanks to @PineappleRind He was the one who showed me these functions. I say why not!

**Comment by PineappleRind** [comment]
👌

**Comment by TheCodingGuru** [comment]
Does this issue deserve to be closed?

**Comment by TheCodingGuru** [comment]
I've closed it, for now.
